[package]
name = "com_library"
version = "0.1.0"
authors = ["Mikko Rantanen <jubjub@jubjubnest.net>"]

[lib]
name = "com_library"
proc-macro = true

[dependencies]
com_runtime = { path = "../com_runtime" }
syn = { version = "0.11", features = [ "full" ] }
quote = { version = "0.3" }
