[package]
name = "intercom-common"
version = "0.1.0"
authors = ["Mikko Rantanen <jubjub@jubjubnest.net>"]
license = "MIT"
repository = "https://github.com/Rantanen/intercom"
description = "See 'intercom'"

[dependencies]
syn = { version = "0.11", features = [ "full" ] }
quote = { version = "0.3" }
sha1 = "0.3.0"
