language: rust
sudo: false
rust:
    - nightly

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc-5
            - g++-5
            - binutils-dev
            - libiberty-dev
env:
    - CC=gcc-5 CXX=g++-5 RUSTFLAGS='-C link-dead-code'

script:
    - (! cargo install clippy --force ) || cargo clippy --all-features --all -- -D warnings
    - cargo test --all-features
    - mkdir build
    - ( cd build && cmake .. && make )
    - ( cd build/bin && ./cpp-raw )
