language: rust
sudo: false
rust:
    - nightly

branches:
    only:
        - master

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - cmake
            - gcc-5
            - g++-5
            - binutils-dev
            - libiberty-dev
            - valgrind
env:
    - CC=gcc-5 CXX=g++-5 RUSTFLAGS='-C link-dead-code'

script:
    - rustup component add clippy rustfmt
    - if( ! cargo clippy -V || ! cargo fmt --version ); then rustup uninstall nightly && rustup toolchain install nightly -c clippy -c rustfmt; fi
    - cargo clippy --all -- -D warnings
    - cargo test
    - mkdir build
    - ( cd build && cmake .. && make )
    - ( cd build/bin && ldd ./cpp-raw && valgrind --error-exitcode=1 --leak-check=full ./cpp-raw )
    - ( cd build/bin && ldd ./cpp-wrapper && valgrind --error-exitcode=1 --leak-check=full ./cpp-wrapper )
    - ( cd build/bin && ldd ./cpp-dl && valgrind --error-exitcode=1 --leak-check=full ./cpp-dl )
