trigger:
- master

strategy:
    matrix:
        Linux:
            imageName: "ubuntu-16.04"
            cmake_generator_opts:
            memcheck: valgrind --error-exitcode=1 --leak-check=full
        Windows:
            imageName: "vs2017-win2016"
            cmake_generator_opts: -DCMAKE_GENERATOR_PLATFORM=x64
            memcheck:

pool:
  vmImage: $(imageName)

steps:
- script: |
    curl -sSf -o rustup-init.exe https://win.rustup.rs
    rustup-init.exe --default-toolchain nightly -y
  displayName: 'Update environment (Windows)'
  condition: and(succeeded(), eq( variables['Agent.OS'], 'Windows_NT' ))

- script: |
    sudo apt-get install valgrind -y
  displayName: 'Update environment (Linux)'
  condition: and(succeeded(), eq( variables['Agent.OS'], 'Linux' ))

- script: |
    rustup -V
    rustup self update
    rustup set profile minimal
    rustup toolchain install nightly -c rustfmt -c clippy
    rustup default nightly
    cargo -V
    rustc -V
    cargo clippy -V
    cargo fmt -- -V
  displayName: 'Setup environment'

- script: cargo fmt -- --check
  displayName: 'Check style'

- script: cargo clippy
  displayName: 'Run build'

- script: cargo test
  displayName: 'Run unit tests'

- script: |
    mkdir build
    cd build
    cmake .. $(cmake_generator_opts)
    cmake --build .
  displayName: "Build integration tests"

- bash: |
    $(memcheck) build/bin/cpp-raw
    $(memcheck) build/bin/cpp-dl
    $(memcheck) build/bin/cpp-wrapper
  displayName: "Run integration tests"
