[package]
name = "calculator"
version = "0.1.0"
authors = ["Mikko Rantanen <jubjub@jubjubnest.net>"]

[lib]
crate-type = [ "cdylib" ]

[dependencies]
com_runtime = { path = "../../com_runtime" }
com_library = { path = "../../com_library" }
