[package]
name = "com_utils"
version = "0.1.0"
authors = ["Mikko Rantanen <jubjub@jubjubnest.net>"]

[dependencies]
syn = { version = "0.11", features = [ "full" ] }
clap = { version = "2.27.1" }
glob = "0.2.11"
if_chain = "0.1.2"
com_common = { path = "../com_common" }
