[package]
name = "intercom_common"
version = "0.1.0"
authors = ["Mikko Rantanen <jubjub@jubjubnest.net>"]

[dependencies]
syn = { version = "0.11", features = [ "full" ] }
quote = { version = "0.3" }
