[package]
name = "intercom"
version = "0.1.0"
authors = ["Mikko Rantanen <jubjub@jubjubnest.net>"]
license = "MIT"
repository = "https://github.com/Rantanen/intercom"
description = "Utilities for writing COM visible Rust components."

[badges]
appveyor = { repository = "Rantanen/intercom", branch = "master", service = "github" }

[lib]
name = "intercom"

[dependencies]
intercom-attributes = { version = "0.1.0", path = "../intercom-attributes" }
