[package]
name = "intercom-attributes"
version = "0.1.0"
authors = ["Mikko Rantanen <jubjub@jubjubnest.net>"]
license = "MIT"
repository = "https://github.com/Rantanen/intercom"
description = "See 'intercom'"

[lib]
name = "intercom_attributes"
proc-macro = true

[dependencies]
intercom-common = { version = "0.1.0", path = "../intercom-common" }
syn = { version = "0.11", features = [ "full" ] }
quote = { version = "0.3" }
