[package]
name = "com_runtime"
version = "0.1.0"
authors = ["Mikko Rantanen <jubjub@jubjubnest.net>"]

[lib]
name = "com_runtime"

[dependencies]
com_common = { path = "../com_common" }
com_library = { path = "../com_library" }
